### ISSUE TITLE
Close the swipe item not working with v0.6.0

### ISSUE THREAD

**Issue by tunm1228** [ambisign-gavin/react-native-swipe-item#22] opened 2022-03-31 07:19 UTC
const itemRef = useRef(null);
...
itemRef.current.close();
...
{
           [].map((item, index) =>
              <SwipeItem
                ref={itemRef}
                key={index}
                style={SWIPE_ITEM}
                swipeContainerStyle={SWIPE_CONTAINER}
                rightButtons={rightButton(item)}
                disableSwipeIfNoButton={true}
              >
               {...}
              </SwipeItem>
            )
 }
itemRef.current.close() => only works on the last word of the array

**Comment by tunm1228** [comment] 2022-03-31 07:40
It works for me! Hoping that this knowledge will be of use to you.
import React, { useRef } from "react";

const arr = [1, 2, 3];

const refs = useRef([])
//refs = {current: []}

const onClick = (index) => {
  console.log(index)
  console.log(refs.current[index])
}

const MyPage = () => {
   const content = arr.map((item, index) => {
     <div key={index} ref={(element) => {refs.current[index] = element}}>
       {item}
       <a
         href="#"
         onClick={(e) => {
           e.preventDefault();
           onClick(index)
         }}
       >
         Review
       </a>
   })
   return content
}

export default MyPage

**Comment by ambisign-gavin** [comment] 2022-04-02 06:57
thanks for your sharing, since it's not a bug and you already solved the problem, I close the issue.

**Closed as completed by ambisign-gavin** 2022-04-02 06:57 UTC
